### ISSUE TITLE
Broken Link to "Reference Guide"

### ISSUE THREAD

**Issue by Kevlar** [AxonFramework/extension-multitenancy#150]
### Basic information

* Axon Framework version: N/A
* JDK version:  N/A
* Multi-Tenancy Extension version: Master as of commit: 585f9c9d15c529d34b811055575c4652987f6735
* Complete executable reproducer if available (e.g. GitHub Repo): N/A

### Steps to reproduce

1. Navigate to:  https://github.com/AxonFramework/extension-multitenancy
2. Scroll down through readme
3. Click the "reference guide link"

### Expected behaviour

Browser navigates to reference guide

### Actual behaviour

Browser navigates to page displaying "page not found" error.

**Comment by Kevlar** [comment]
Additionally, the link to https://github.com/AxonFramework/extension-multitenancy/blob/main/MultiTenantDataSourceManager.java also doesn't work for me.

**Comment by smcvb** [comment]
Thanks for filing this concern with us, @Kevlar! I've resolved the predicament you describe here, and the one you've opened (and closed) in pull request #149.
