### ISSUE TITLE
Simple command bus is reused for every tenant

### ISSUE THREAD

**Issue by schananas** [AxonFramework/extension-multitenancy#173]
Same local segment command bus is reused between tenant axon server command segments. And then if I add handler interceptor to the multitenant bus, it applies on each tenant command bus when it is started and each tenant bus applies it on a single instance of the local segment bus. As a result if you have N tenants, your local segment bus will have N same handler interceptors.

Wanted behaviour:
Each tenant segment should have its own simple command bus. In our case tenant segment has its own axon server command bus, but axon server command bus uses shared command bus, that causes this issue.

**Comment by zistow** [comment]
When it will be fixed?

Refers to: https://discuss.axoniq.io/t/multitenancy-extension-multiplied-command-bus-message-handlers-interceptors/5679/2

**Comment by smcvb** [comment]
Thanks for refreshing me here, @zistow. We've been spread thin a little the past months on the Axon Framework Extensions, so my apologies for the wait.
I'll contact @schananas once he's available to discuss how and when we'll proceed with this fix and the other issues you've constructed.

From here, we'll keep you up to date by adjusting **this** issue accordingly.

**Comment by smcvb** [comment]
Closing this issue since it's been solved by #221.
