### ISSUE TITLE
Remove tokens when a tenant is removed.

### ISSUE THREAD

**Issue by gklijs** [AxonFramework/extension-multitenancy#196]
### Basic information

* Axon Framework version: not relevant
* JDK version: not relevant
* Multi-Tenancy Extension version: not relevant
* Complete executable reproducer if available (e.g. GitHub Repo): not relevant

### Steps to reproduce

Create a tennent, remove and create a tennent with the same name. While the projections and events are removed, event processing will be 'stuck' where it was left since the tokens aren't removed.

### Expected behaviour

Tokens are removed in the `stopAndRemoveTenant` method of the `MultiTenantEventProcessor`

### Actual behaviour

Event processors are shut down, but the related tokens aren't deleted.

**Comment by schananas** [comment]
Extension is not responsible of deleting anything, its up to user to clean up any tenant data, such as events, contexts, tokens  etc. Therefor closing this ticket

**Comment by gklijs** [comment]
Shouldn't the method then be renamed to just `stopTenant`?
