### ISSUE TITLE
Multitenancy Extension - shutdown handler

### ISSUE THREAD

**Issue by zistow** [AxonFramework/extension-multitenancy#215]
Refers to: https://discuss.axoniq.io/t/multitenancy-extension-shutdown-handler/5654

**Comment by smcvb** [comment]
@zistow, would you mind expanding the description to contain all the valuable information from the referred to discuss issue?
As it is, this ticket is unclear. Thanks for your help!

**Comment by schananas** [comment]
Solved with https://github.com/AxonFramework/extension-multitenancy/pull/228
