### ISSUE TITLE
Remove the use of  @PostConstruct

### ISSUE THREAD

**Issue by gklijs** [AxonFramework/extension-multitenancy#93]
### Basic information

The `javax.annotation.PostConstruct` annotation is used in two places. This will not work with Jakarta/Spring boot 3.

### Steps to reproduce

Use the extension in a Spring Boot 3 project. Since the `AxonServerTenantProvider` will never start, it will never find any context/tenant.

### Expected behaviour

It works properly, also with Spring Boot 3 / Jakarta.
Alternatively the AF `Lifecycle` interface can be used to start.

### Actual behaviour

It doesn't start the `AxonServerTenantProvider` or the `CloudTenantProvider`.

**Comment by schananas** [comment]
This is no closed, right?
